version: "3.8"
services:

  db:
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db}
      MYSQL_USER: ${MYSQL_USER:-dbusr}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dbpwd}
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - ./container-data/mysql-${MYSQL_VERSION:-8.0}:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    environment:
      VIRTUAL_HOST: ${ADMINER_VIRTUAL_HOST}
    depends_on:
      - proxy
